export const COUNTRY_LIST = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Belgique",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Biélorussie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "République centrafricaine",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "Costa Rica",
  "Côte d’Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "République dominicaine",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "Eswatini",
  "États-Unis",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Liberia",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Îles Marshall",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Christophe-et-Niévès",
  "Sainte-Lucie",
  "Saint-Marin",
  "Saint-Vincent-et-les-Grenadines",
  "Salomon",
  "Salvador",
  "Samoa",
  "Sao Tomé-et-Principe",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "République tchèque",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Yémen",
  "Zambie",
  "Zimbabwe",
  "Palestine",
];

export const COUNTRY_CALLING_CODES = [
  { country: "Afghanistan", code: "+93" },
  { country: "Afrique du Sud", code: "+27" },
  { country: "Albanie", code: "+355" },
  { country: "Algérie", code: "+213" },
  { country: "Allemagne", code: "+49" },
  { country: "Andorre", code: "+376" },
  { country: "Angola", code: "+244" },
  { country: "Antigua-et-Barbuda", code: "+1-268" },
  { country: "Arabie saoudite", code: "+966" },
  { country: "Argentine", code: "+54" },
  { country: "Arménie", code: "+374" },
  { country: "Australie", code: "+61" },
  { country: "Autriche", code: "+43" },
  { country: "Azerbaïdjan", code: "+994" },
  { country: "Bahamas", code: "+1-242" },
  { country: "Bahreïn", code: "+973" },
  { country: "Bangladesh", code: "+880" },
  { country: "Barbade", code: "+1-246" },
  { country: "Belgique", code: "+32" },
  { country: "Belize", code: "+501" },
  { country: "Bénin", code: "+229" },
  { country: "Bhoutan", code: "+975" },
  { country: "Biélorussie", code: "+375" },
  { country: "Bolivie", code: "+591" },
  { country: "Bosnie-Herzégovine", code: "+387" },
  { country: "Botswana", code: "+267" },
  { country: "Brésil", code: "+55" },
  { country: "Brunei", code: "+673" },
  { country: "Bulgarie", code: "+359" },
  { country: "Burkina Faso", code: "+226" },
  { country: "Burundi", code: "+257" },
  { country: "Cambodge", code: "+855" },
  { country: "Cameroun", code: "+237" },
  { country: "Canada", code: "+1" },
  { country: "Cap-Vert", code: "+238" },
  { country: "République centrafricaine", code: "+236" },
  { country: "Chili", code: "+56" },
  { country: "Chine", code: "+86" },
  { country: "Chypre", code: "+357" },
  { country: "Colombie", code: "+57" },
  { country: "Comores", code: "+269" },
  { country: "République du Congo", code: "+242" },
  { country: "République démocratique du Congo", code: "+243" },
  { country: "Costa Rica", code: "+506" },
  { country: "Côte d’Ivoire", code: "+225" },
  { country: "Croatie", code: "+385" },
  { country: "Cuba", code: "+53" },
  { country: "Danemark", code: "+45" },
  { country: "Djibouti", code: "+253" },
  { country: "Dominique", code: "+1-767" },
  { country: "République dominicaine", code: "+1-809" },
  { country: "Égypte", code: "+20" },
  { country: "Émirats arabes unis", code: "+971" },
  { country: "Équateur", code: "+593" },
  { country: "Érythrée", code: "+291" },
  { country: "Espagne", code: "+34" },
  { country: "Estonie", code: "+372" },
  { country: "Eswatini", code: "+268" },
  { country: "États-Unis", code: "+1" },
  { country: "Éthiopie", code: "+251" },
  { country: "Fidji", code: "+679" },
  { country: "Finlande", code: "+358" },
  { country: "France", code: "+33" },
  { country: "Gabon", code: "+241" },
  { country: "Gambie", code: "+220" },
  { country: "Géorgie", code: "+995" },
  { country: "Ghana", code: "+233" },
  { country: "Grèce", code: "+30" },
  { country: "Grenade", code: "+1-473" },
  { country: "Guatemala", code: "+502" },
  { country: "Guinée", code: "+224" },
  { country: "Guinée-Bissau", code: "+245" },
  { country: "Guinée équatoriale", code: "+240" },
  { country: "Guyana", code: "+592" },
  { country: "Haïti", code: "+509" },
  { country: "Honduras", code: "+504" },
  { country: "Hongrie", code: "+36" },
  { country: "Inde", code: "+91" },
  { country: "Indonésie", code: "+62" },
  { country: "Irak", code: "+964" },
  { country: "Iran", code: "+98" },
  { country: "Irlande", code: "+353" },
  { country: "Islande", code: "+354" },
  { country: "Israël", code: "+972" },
  { country: "Italie", code: "+39" },
  { country: "Jamaïque", code: "+1-876" },
  { country: "Japon", code: "+81" },
  { country: "Jordanie", code: "+962" },
  { country: "Kazakhstan", code: "+7" },
  { country: "Kenya", code: "+254" },
  { country: "Kirghizistan", code: "+996" },
  { country: "Kiribati", code: "+686" },
  { country: "Koweït", code: "+965" },
  { country: "Laos", code: "+856" },
  { country: "Lesotho", code: "+266" },
  { country: "Lettonie", code: "+371" },
  { country: "Liban", code: "+961" },
  { country: "Liberia", code: "+231" },
  { country: "Libye", code: "+218" },
  { country: "Liechtenstein", code: "+423" },
  { country: "Lituanie", code: "+370" },
  { country: "Luxembourg", code: "+352" },
  { country: "Macédoine du Nord", code: "+389" },
  { country: "Madagascar", code: "+261" },
  { country: "Malaisie", code: "+60" },
  { country: "Malawi", code: "+265" },
  { country: "Maldives", code: "+960" },
  { country: "Mali", code: "+223" },
  { country: "Malte", code: "+356" },
  { country: "Maroc", code: "+212" },
  { country: "Îles Marshall", code: "+692" },
  { country: "Maurice", code: "+230" },
  { country: "Mauritanie", code: "+222" },
  { country: "Mexique", code: "+52" },
  { country: "Micronésie", code: "+691" },
  { country: "Moldavie", code: "+373" },
  { country: "Monaco", code: "+377" },
  { country: "Mongolie", code: "+976" },
  { country: "Monténégro", code: "+382" },
  { country: "Mozambique", code: "+258" },
  { country: "Myanmar", code: "+95" },
  { country: "Namibie", code: "+264" },
  { country: "Nauru", code: "+674" },
  { country: "Népal", code: "+977" },
  { country: "Nicaragua", code: "+505" },
  { country: "Niger", code: "+227" },
  { country: "Nigeria", code: "+234" },
  { country: "Norvège", code: "+47" },
  { country: "Nouvelle-Zélande", code: "+64" },
  { country: "Oman", code: "+968" },
  { country: "Ouganda", code: "+256" },
  { country: "Ouzbékistan", code: "+998" },
  { country: "Pakistan", code: "+92" },
  { country: "Palaos", code: "+680" },
  { country: "Panama", code: "+507" },
  { country: "Papouasie-Nouvelle-Guinée", code: "+675" },
  { country: "Paraguay", code: "+595" },
  { country: "Pays-Bas", code: "+31" },
  { country: "Pérou", code: "+51" },
  { country: "Philippines", code: "+63" },
  { country: "Pologne", code: "+48" },
  { country: "Portugal", code: "+351" },
  { country: "Qatar", code: "+974" },
  { country: "Roumanie", code: "+40" },
  { country: "Royaume-Uni", code: "+44" },
  { country: "Russie", code: "+7" },
  { country: "Rwanda", code: "+250" },
  { country: "Saint-Christophe-et-Niévès", code: "+1-869" },
  { country: "Sainte-Lucie", code: "+1-758" },
  { country: "Saint-Marin", code: "+378" },
  { country: "Saint-Vincent-et-les-Grenadines", code: "+1-784" },
  { country: "Salomon", code: "+677" },
  { country: "Salvador", code: "+503" },
  { country: "Samoa", code: "+685" },
  { country: "Sao Tomé-et-Principe", code: "+239" },
  { country: "Sénégal", code: "+221" },
  { country: "Serbie", code: "+381" },
  { country: "Seychelles", code: "+248" },
  { country: "Sierra Leone", code: "+232" },
  { country: "Singapour", code: "+65" },
  { country: "Slovaquie", code: "+421" },
  { country: "Slovénie", code: "+386" },
  { country: "Somalie", code: "+252" },
  { country: "Soudan", code: "+249" },
  { country: "Soudan du Sud", code: "+211" },
  { country: "Sri Lanka", code: "+94" },
  { country: "Suède", code: "+46" },
  { country: "Suisse", code: "+41" },
  { country: "Suriname", code: "+597" },
  { country: "Syrie", code: "+963" },
  { country: "Tadjikistan", code: "+992" },
  { country: "Tanzanie", code: "+255" },
  { country: "Tchad", code: "+235" },
  { country: "République tchèque", code: "+420" },
  { country: "Thaïlande", code: "+66" },
  { country: "Timor oriental", code: "+670" },
  { country: "Togo", code: "+228" },
  { country: "Tonga", code: "+676" },
  { country: "Trinité-et-Tobago", code: "+1-868" },
  { country: "Tunisie", code: "+216" },
  { country: "Turkménistan", code: "+993" },
  { country: "Turquie", code: "+90" },
  { country: "Tuvalu", code: "+688" },
  { country: "Ukraine", code: "+380" },
  { country: "Uruguay", code: "+598" },
  { country: "Vanuatu", code: "+678" },
  { country: "Vatican", code: "+379" },
  { country: "Venezuela", code: "+58" },
  { country: "Vietnam", code: "+84" },
  { country: "Yémen", code: "+967" },
  { country: "Zambie", code: "+260" },
  { country: "Zimbabwe", code: "+263" },
  { country: "Palestine", code: "+970" },
];
