export const PAGE_CATEGORY_GROUPS = [
  {
    label: "Entreprise & Business",
    options: [
      "Entreprise",
      "Startup",
      "PME / PMI",
      "Multinationale",
      "Holding",
      "Cabinet de conseil",
      "Cabinet juridique",
      "Cabinet comptable",
      "Société de services",
      "Agence de recrutement",
      "Cabinet RH",
      "Cabinet d’audit",
      "Entreprise BTP",
      "Société industrielle",
      "Société commerciale",
      "Entreprise de transport & logistique",
      "Entreprise agricole",
      "Entreprise minière",
      "Société immobilière",
      "Entreprise de nettoyage",
      "Entreprise de sécurité",
    ],
  },
  {
    label: "Emploi & Carrière",
    options: [
      "Offres d’emploi",
      "Recrutement",
      "Freelance / Indépendant",
      "Stage & alternance",
      "Cabinet de placement",
      "Coaching professionnel",
      "Orientation professionnelle",
      "Formation professionnelle",
      "CV & Lettres de motivation",
      "Ressources humaines",
      "Intérim",
      "Portage salarial",
    ],
  },
  {
    label: "Éducation & Formation",
    options: [
      "Université",
      "École supérieure",
      "Lycée / Collège",
      "Centre de formation",
      "Formation en ligne",
      "Bootcamp",
      "École technique",
      "Centre de certification",
      "Institut professionnel",
      "Formation IT",
      "Formation BTP",
      "Formation santé",
      "Formation entrepreneuriat",
    ],
  },
  {
    label: "BTP & Construction",
    options: [
      "Entreprise BTP",
      "Génie civil",
      "Travaux publics",
      "Architecture",
      "Bureau d’études",
      "Immobilier & construction",
      "Maçonnerie",
      "Électricité bâtiment",
      "Plomberie",
      "Menuiserie",
      "Peinture",
      "Carrelage",
      "Climatisation",
      "Topographie",
    ],
  },
  {
    label: "Santé & Social",
    options: [
      "Hôpital",
      "Clinique",
      "Centre médical",
      "Cabinet médical",
      "Pharmacie",
      "Laboratoire",
      "ONG santé",
      "Centre de soins",
      "Association humanitaire",
      "Médecine du travail",
      "Centre psychologique",
    ],
  },
  {
    label: "Technologie & Numérique",
    options: [
      "Startup tech",
      "Développement web",
      "Développement mobile",
      "Logiciel & SaaS",
      "Cybersécurité",
      "Intelligence artificielle",
      "Data & Big Data",
      "Cloud computing",
      "Hébergement web",
      "Agence digitale",
      "Marketing digital",
      "UX/UI Design",
      "E-commerce",
    ],
  },
  {
    label: "Administration & Institution",
    options: [
      "Institution publique",
      "Ministère",
      "Collectivité territoriale",
      "Mairie",
      "Organisation gouvernementale",
      "Organisation internationale",
      "Ambassade",
      "Chambre de commerce",
      "Organisation patronale",
      "Syndicat",
    ],
  },
  {
    label: "Commerce & Services",
    options: [
      "Boutique",
      "Supermarché",
      "Commerce en ligne",
      "Grossiste",
      "Distributeur",
      "Import / Export",
      "Service client",
      "Service après-vente",
      "Vente au détail",
      "Marketplace",
    ],
  },
  {
    label: "Création, Média & Communication",
    options: [
      "Média",
      "Journal",
      "Télévision",
      "Radio",
      "Agence de communication",
      "Studio de création",
      "Photographie",
      "Vidéo & audiovisuel",
      "Influenceur",
      "Créateur de contenu",
      "Graphisme",
      "Impression",
    ],
  },
  {
    label: "Restauration & Hôtellerie",
    options: [
      "Restaurant",
      "Fast-food",
      "Café",
      "Bar",
      "Hôtel",
      "Auberge",
      "Traiteur",
      "Pâtisserie",
      "Boulangerie",
      "Street food",
    ],
  },
  {
    label: "Transport & Mobilité",
    options: [
      "Transport public",
      "Transport privé",
      "VTC / Taxi",
      "Logistique",
      "Livraison",
      "Location de véhicules",
      "Garage automobile",
      "Auto-école",
      "Transport maritime",
      "Transport aérien",
    ],
  },
  {
    label: "ONG, Associations & Communautés",
    options: [
      "ONG",
      "Association",
      "Coopérative",
      "Fondation",
      "Organisation caritative",
      "Organisation communautaire",
      "Association professionnelle",
      "Club",
      "Réseau professionnel",
    ],
  },
  {
    label: "Culture, Sport & Loisirs",
    options: [
      "Club sportif",
      "Salle de sport",
      "Événement sportif",
      "Fédération",
      "Association culturelle",
      "Art & culture",
      "Cinéma",
      "Musique",
      "Théâtre",
      "Festival",
    ],
  },
  {
    label: "Profil professionnel",
    options: [
      "Entrepreneur",
      "Freelance",
      "Consultant",
      "Coach",
      "Formateur",
      "Expert métier",
      "Conférencier",
      "Auteur",
      "personnalité publique",
      "Influenceur professionnel",
    ],
  },
];
